# Generated by Django 3.1.5 on 2021-01-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='date happened')),
                ('user_id', models.CharField(max_length=16)),
                ('content_id', models.CharField(max_length=16)),
                ('event', models.CharField(max_length=200)),
                ('session_id', models.CharField(max_length=128)),
            ],
        ),
    ]
